cmake_minimum_required(VERSION 3.16)
project(gs2020_marinelli CXX)
set(CMAKE_CXX_STANDARD 17)
if(NOT G4ROOT OR NOT XERCESC_ROOT)
  message(FATAL_ERROR "нужны -DG4ROOT и -DXERCESC_ROOT")
endif()
file(GLOB G4_IMPORT_LIBS "${G4ROOT}/lib/*.lib")
file(GLOB XERCESC_IMPORT_LIBS "${XERCESC_ROOT}/lib/*.lib")
add_executable(gs2020_marinelli main.cc)
target_include_directories(gs2020_marinelli PRIVATE "${G4ROOT}/include/Geant4" "${XERCESC_ROOT}/include")
target_link_libraries(gs2020_marinelli PRIVATE ${G4_IMPORT_LIBS} ${XERCESC_IMPORT_LIBS})
target_compile_definitions(gs2020_marinelli PRIVATE G4LIB_BUILD_DLL WIN32 NOMINMAX _USE_MATH_DEFINES)
target_compile_options(gs2020_marinelli PRIVATE /EHsc /MD /bigobj /utf-8 /wd4005 /wd4267 /wd4244)
